### ISSUE TITLE
FR: Prompt Support CVS

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Inspire-Pack#12]
The current prompt reading requires a file per prompt, which is painful when I have a set of 1000 prompts already in a CSV file.  Can we have CSV as another option here, and perhaps a use of something like comply for prompt weighting and negative use?  Getting all of the prompts into one file is the primary pain point I am trying to resolve.

**Comment by ltdrdata** [comment]
Can you provide the sample of .csv? I'll support that format.

**Comment by ltdrdata** [comment]
> How about something simple like: "long spaceship in orbit around a gas giant planet:0.7|stars in the galaxy:-0.5",
> 
> you could allow someone to specify aspects of the CSV as well, just pondering how a positive and negative could work in a simple manner.

It seems there isn't an existing format in use. Using a `.csv` format might not be suitable since it uses a comma (,) as a separator, and this could lead to confusion because the comma is frequently used in prompts. If the goal is simply to store multiple sets of pos/neg prompts in one file, I'll consider a proper format.

**Comment by ltdrdata** [comment]
`Load Prompts From File`  is added. 692d26d0e5e27a4192b11be209e1d9660d95d5a3

`|` can be confused with dynamic prompts, and for compatibility with the existing `Load Prompts From Dir` format, I've defined the format as `prompt: blahblah negative: blahblah`. The delimiter between prompts is `----`.

**Comment by sedetweiler** [comment]
Okay, thank you.
