### ISSUE TITLE
Lora Loader (Block Weight) has a bug on applying preset or block value

### ISSUE THREAD

**Issue by lgh5509** [ltdrdata/ComfyUI-Inspire-Pack#132]
![Block Weight bug_1](https://github.com/user-attachments/assets/7dcc039a-3eb9-4a5b-abbe-c3b8c43c4a22)
![Block Weight bug_2](https://github.com/user-attachments/assets/3f523dad-65c9-4ba5-baa0-8ca21a6030d1)
![Block Weight bug_3](https://github.com/user-attachments/assets/ad3d9421-88b9-42f2-a172-99980e1bd462)
![Block Weight bug_4](https://github.com/user-attachments/assets/d42623de-2137-43a2-ba10-230dd72c0416)

Hello, first of all, thank you for making wonderful Nodes.

you are part of great light of human history.

and get to the point, the Lora Loader (Block Weight)'s Block 1 is always applying value 1. regardless of any value or presets.

could you please help this problem?

**Comment by SeekerOfTheThicc** [comment]
So I have been exploring LoRA block weights, and in the course of learning about lbw I came across this post because #1- I ran into the same problem, and #2 I have been trying to discover the reason behind getting different results using the same lbw values (copy and pasted basically) when using [PowerMerger](https://github.com/larsupb/LoRA-Merger-ComfyUI/tree/main) and this node. (short answer: different developers implement things differently) 

During my travels I believe I have found an explanation for you, so I found this post again so I can share what I learned.  The short version: that appears to be the text encoder block.  If you want to control the strength of that block you will have to use "strength clip" above.  As far as I can tell, there is no way to modify the weight of the text encoder blocks or sub blocks in this node- you can only change the overall strength.

**Comment by ltdrdata** [comment]
> So I have been exploring LoRA block weights, and in the course of learning about lbw I came across this post because 1- I ran into the same problem, and 2 I have been trying to discover the reason behind getting different results using the same lbw values (copy and pasted basically) when using [PowerMerger](https://github.com/larsupb/LoRA-Merger-ComfyUI/tree/main) and this node. (short answer: different developers implement things differently)
> 
> During my travels I believe I have found an explanation for you, so I found this post again so I can share what I learned. The short version: that appears to be the text encoder block. If you want to control the strength of that block you will have to use "strength clip" above. As far as I can tell, there is no way to modify the weight of the text encoder blocks or sub blocks in this node- you can only change the overall strength.

That was not the intention. It has now been fixed and patched so that the base block weight has an effect.
