### ISSUE TITLE
Possible issue with Image Loader

### ISSUE THREAD

**Issue by var1ableX** [ltdrdata/ComfyUI-Inspire-Pack#25]
Not sure if this is an actual bug but is it possible Inspire Pack Image Loader places heavier resource requirements on Comfyui relative to the vanilla image loader?

A couple of times in the last week or so when I've loaded images via Inspire Pack image loader Comfyui starts to respond slowly and eventually becomes non-responsive. When I check the logs I notice large amounts of encoded data. Initially i thought it was the size of images I'd placed in CLIPspace. However, last night I seemed to fix the issue by deleting the Inspire Image Loader and replacing it with vanilla (same images though). After reverting to Vanilla Loader I also went into log, and cleared it in case Comfyui is allocating background resources to maintaining the log.

**Comment by ltdrdata** [comment]
> Not sure if this is an actual bug but is it possible Inspire Pack Image Loader places heavier resource requirements on Comfyui relative to the vanilla image loader?
> 
> A couple of times in the last week or so when I've loaded images via Inspire Pack image loader Comfyui starts to respond slowly and eventually becomes non-responsive. When I check the logs I notice large amounts of encoded data. Initially i thought it was the size of images I'd placed in CLIPspace. However, last night I seemed to fix the issue by deleting the Inspire Image Loader and replacing it with vanilla (same images though). After reverting to Vanilla Loader I also went into log, and cleared it in case Comfyui is allocating background resources to maintaining the log.

The `Load Image (Inspire)` node is not created to replace the vanilla image loader. It is designed for a specific purpose, which is to store images in the workflow. Because image information is encoded and stored in the workflow, it leads to increased resource consumption. This node is intended to ensure that the loaded images are included when the workflow is shared with others or when images need to be preserved even if deleted to reproduce.

Its primary purpose is for creating tutorial workflows or test workflows.
