### ISSUE TITLE
the HyperTile (Inspire) node isn't actually usable

### ISSUE THREAD

**Issue by blepping** [ltdrdata/ComfyUI-Inspire-Pack#67]
because it has a bunch of debug prints, including printing out the actual tensors. i have a version adapted from yours here: https://github.com/blepping/ComfyUI-bleh/blob/main/py/hypertile.py

i also verified that it produces the same results as the built in ComfyUI one. my version also adds the ability to set an interval and timestep range. one solution to the problem would be to just take my version (and possibly remove the interval/timestep stuff if you don't want it)

**Comment by ltdrdata** [comment]
It's currently stalled at the testing stage. I found that it yields different results from the original A1111's hypertile, and discovered that the shape of the tile changes during the application process. Although it was intended as an alternative solution for this, it failed due to differences on the core side as well.

So, it's a node that's currently under consideration.

**Comment by blepping** [comment]
sorry, kind of forgot about this one. i'll just close it, but if the node isn't usable and is only for your own testing then it would probably be better to disable it for users or at least include something like `(testing only)` in the title.
