### ISSUE TITLE
Image batch from directory crops images.

### ISSUE THREAD

**Issue by RangerFrank** [ltdrdata/ComfyUI-Inspire-Pack#97]
Image batch crops images making it useless.

**Comment by ltdrdata** [comment]
That's the nature of the `image batch`. A batch is represented as a single data with four dimensions: `batch size * height * width * channel`. This means that all images in the batch must have the same resolution.
Typically, this is used for processing things like video frame images.

If you want to process images of varying resolutions, you should use an image list instead of an image batch. An image list separates images one by one to execute separate workflows.
